# -*- coding: utf-8 -*-
"""Detecting Spam Emails Using Tensorflow in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1komogd62FwsVbkGniFEDt8Fm6_eXR8Bm
"""

# Install wordcloud if not available
pip install wordcloud

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string
import nltk
from nltk.corpus import stopwords
from wordcloud import WordCloud

nltk.download('stopwords')

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

import warnings
warnings.filterwarnings('ignore')
import subprocess
subprocess.run(["pip", "install", "wordcloud"], check=True)

print("TF Version:", tf.__version__)

pip install wordcloud

# Option 1: Upload manually
from google.colab import files
uploaded = files.upload()  # Upload your spam.csv here

# Option 2: Download from URL (SMS Spam Collection)
!wget -q "https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip"
!unzip -q smsspamcollection.zip

df = pd.read_csv('SMSSpamCollection', sep='\t', names=['label', 'message'])
df.head()

# Shape and info
print(df.shape)
print(df['label'].value_counts())

# Visualize class distribution
sns.countplot(x='label', data=df)
plt.title("Spam vs Ham Distribution")
plt.show()

# WordCloud for Spam
spam_words = ' '.join(df[df['label'] == 'spam']['message'])
wordcloud = WordCloud(width=600, height=300, background_color='black').generate(spam_words)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Spam WordCloud")
plt.show()

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = ''.join([ch for ch in text if ch not in string.punctuation])
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

df['clean_message'] = df['message'].apply(clean_text)

# Encode labels: spam=1, ham=0
df['label_enc'] = df['label'].map({'spam': 1, 'ham': 0})
df.head()

MAX_VOCAB = 10000
MAX_LEN   = 150

tokenizer = Tokenizer(num_words=MAX_VOCAB, oov_token='<OOV>')
tokenizer.fit_on_texts(df['clean_message'])

sequences = tokenizer.texts_to_sequences(df['clean_message'])
padded    = pad_sequences(sequences, maxlen=MAX_LEN, truncating='post', padding='post')

print("Padded shape:", padded.shape)

X = padded
y = df['label_enc'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train:", X_train.shape, "Test:", X_test.shape)

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=MAX_VOCAB, output_dim=64, input_length=MAX_LEN),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=True)),
    tf.keras.layers.GlobalMaxPooling1D(),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

callbacks = [
    EarlyStopping(patience=3, restore_best_weights=True),
    ReduceLROnPlateau(factor=0.5, patience=2, min_lr=1e-6)
]

history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.1,
    callbacks=callbacks
)

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy*100:.2f}%")

# Plot accuracy & loss curves
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Acc')
plt.plot(history.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss')
plt.legend()

plt.show()